=== Lukas-Clifford/redacciones/trabajoXML/validacion.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="trabajo">

        <xs:complexType>
            <xs:sequence>
                <xs:element name="cabecera">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="tituloDocumento" type="xs:string"/>
                            <xs:element name="subtitulo" type="xs:string"/>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="seccion" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="titulo" type="xs:string"/>

                            <xs:element name="contenido">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">

                                        <xs:element name="subtitulo" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>

                                        <xs:element name="parrafo" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>

                                        <xs:element name="lista" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="item" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>

                                        </xs:element>

                                        <xs:element name="ejemplo" minOccurs="0" maxOccurs="unbounded" type="xs:string" />

                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>



    </xs:element>
</xs:schema>

=== Lukas-Clifford/redacciones/trabajoXML/index.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="estilo.css"?>



<trabajo

xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com/xml validacion.xsd">
    
    <cabecera>
        <tituloDocumento>XML</tituloDocumento>
        <subtitulo>Lukas Clifford Vogdt Torralba</subtitulo>
    </cabecera>
    
    
    <seccion>

        <titulo>¿Qué es XML?</titulo>

        <contenido>

            <parrafo>El lenguaje de marcado extensible es, como dice su nombre, un lenguaje de marcas que no se basa en un conjunto de etiquetas como hace HTML. En XML las etiquetas son creadas acorde a la necesidad del sistema.</parrafo>
            <parrafo>Se utiliza para el almacenamiento e intercambio de datos de una manera estructurada entre distintas plataformas.</parrafo>
            <parrafo>Es un lenguaje “padre”, que de él, salen muchos lenguajes “hijos” llamados dialectos XML. Algunos son:</parrafo>

            <lista>
                <item>MathML para hacer expresiones matemáticas</item>
                <item>SVG para hacer gráficos vectoriales</item>
                <item>GML para información geográfica</item>
            </lista>

        </contenido>
    </seccion>

    <seccion>
        <titulo>Cómo se escribe</titulo>
        <contenido>
            <subtitulo>Etiquetas</subtitulo>

            <parrafo>Se utilizan los signos &lt;&gt; y / para definir etiquetas.</parrafo>
            <ejemplo>
    &lt;etiqueta ejemplo&gt;&lt;/etiqueta ejemplo&gt;
            </ejemplo>
            <parrafo>Además, si un elemento no contiene un valor se puede escribir:</parrafo>
            <ejemplo>
    &lt;etiqueta-sin-valor/&gt;
            </ejemplo>

            <parrafo>Los nombres de los elementos son case sensitive y tienen que cumplir las siguientes normas:</parrafo>
            <lista>
                <item>Pueden tener letras minúsculas, mayúsculas, números, puntos, guiones medios y guiones bajos.</item>
                <item>Pueden tener el carácter dos puntos pero su uso es para definir namespaces.</item>
                <item>El primer carácter tiene que ser una letra o guión bajo.</item>
            </lista>
            <parrafo>Letras no inglesas permitidas pero no aconsejables.
                Guión medio y punto, tampoco aconsejables. El guión porque se puede confundir con el símbolo de resta y el punto porque se puede interpretar como propiedades de objeto (objeto.propiedad)</parrafo>


            <subtitulo>Estructura</subtitulo>
            <parrafo>Los documentos XML se organizan en una estructura de árbol invertido con elementos padre y elementos hijos. Por ejemplo, cada sección de este documento tiene (no obligatoriamente todos):</parrafo>
            <ejemplo>
    Sección
    ├── subtitulo
    ├── párrafo
    ├── lista
    │   └── item
    └── ejemplo
            </ejemplo>

            <parrafo>Además, un elemento puede contener contenido mixto como: </parrafo>
            <ejemplo>
    &lt;nombre&gt;Lukas&lt;/nombre&gt; estudia en el IES &lt;Instituto&gt;Gran Capitán&lt;/Instituto&gt;
            </ejemplo>

            <subtitulo>Atributos</subtitulo>
            <parrafo>Los atributos son información extra que se le puede añadir al elemento que los contiene. Se definen en la etiqueta de inicio y siguen las mismas normas sintácticas que los nombres de los elementos. Además, deben tener nombres únicos dentro del elemento.</parrafo>
            <ejemplo>
    &lt;punto x="2" y="4"/&gt;
            </ejemplo>

            <subtitulo>Referencias a Caracteres Especiales</subtitulo>
            <parrafo>En XML, existen ciertos caracteres con un significado especial, como &lt;, &gt;, &amp;, " y ', que no pueden usarse directamente en el contenido de los elementos. Para representarlos correctamente, se emplean referencias a entidades, que permiten que los procesadores de XML los interpreten sin errores.</parrafo>
            <lista>
                <item>&lt; se representa como &amp;lt;</item>
                <item>&gt; se representa como &amp;gt;</item>
                <item>&amp; se representa como &amp;amp;</item>
                <item>" se representa como &amp;quot;</item>
                <item>' se representa como &amp;apos;</item>
            </lista>
            <parrafo>Además, se pueden utilizar referencias numéricas Unicode para representar cualquier carácter especial usando &amp;# seguido del código decimal o hexadecimal del carácter.</parrafo>


            <subtitulo>Comentarios en XML</subtitulo>
            <parrafo>Los comentarios permiten agregar notas dentro del código XML sin afectar su funcionamiento. Se escriben entre &lt;!-- y --&gt;. Sin embargo, hay ciertas restricciones:</parrafo>
            <lista>
                <item>No pueden incluir dos guiones consecutivos (--).</item>
                <item>No se pueden anidar comentarios dentro de otros comentarios.</item>
                <item>No deben incluirse dentro de etiquetas.</item>
            </lista>
            <ejemplo>
    &lt;!-- Esto es un comentario en XML --&gt;
            </ejemplo>

            <subtitulo>Instrucciones de procesamiento</subtitulo>
            <parrafo>Sirven para indicar información al programa que procese el documento. Se escriben con &lt;? y ?&gt;. Una instrucción de procesamiento común es la declaración XML que, si aparece, está siempre en la primera línea</parrafo>
            <ejemplo>
    &lt;!-- Declaración XML --&gt;
    &lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?&gt;

    &lt;!-- Asignación de hoja de estilos --&gt;
    &lt;?xml-stylesheet type="text/css" href="nombre_estilo.css"?&gt;
            </ejemplo>

            <subtitulo>Namespaces en XML</subtitulo>
            <parrafo>Los namespaces (espacios de nombres) en XML evitan conflictos entre etiquetas cuando se combinan diferentes esquemas XML en un mismo documento. Se declaran usando el atributo xmlns.</parrafo>
            <ejemplo>
    &lt;documento xmlns:h="http://www.ejemplo.com/html"&gt;
    &lt;h:titulo&gt;Mi Documento&lt;/h:titulo&gt;
    &lt;/documento&gt;
            </ejemplo>
            <parrafo>En este caso, el prefijo h hace referencia al namespace definido en la URL, lo que evita confusión si existen etiquetas titulo en otros contextos.</parrafo>

            <subtitulo>Documentos XML bien formados y válidos</subtitulo>
            <parrafo>Un documento XML bien formado es aquel que cumple con las reglas básicas de sintaxis.</parrafo>
            <lista>
                <item>Todos los elementos deben tener una etiqueta de apertura y una de cierre.</item>
                <item>Las etiquetas deben estar correctamente anidadas.</item>
                <item>Solo puede haber un elemento raíz.</item>
                <item>Los nombres de elementos y atributos deben seguir las reglas sintácticas de XML.</item>
                <item>Los valores de los atributos deben ir entre comillas.</item>
            </lista>
            <parrafo>Un documento XML válido no solo debe estar bien formado, sino que también debe ajustarse a una estructura definida mediante DTD o XSD.</parrafo>


        </contenido>
    </seccion>
    
    <seccion>
        <titulo>Document Type Definition</titulo>
        <contenido>
            <parrafo>DTD es un mecanismo que define la estructura y reglas que debe cumplir un documento XML para ser válido. Se puede incluir dentro del propio documento o en un archivo externo. Un documento XML será válido cuando, además de estar bien formado, respete las normas establecidas en su DTD.</parrafo>

            <subtitulo>DTD interna</subtitulo>
                <parrafo>Se incluye dentro del propio documento XML. Se utiliza cuando la estructura solo es necesaria para un único documento.</parrafo>
            <ejemplo>
    &lt;!DOCTYPE saludo [&lt;!ELEMENT saludo (#PCDATA)&gt;]&gt;
    &lt;saludo&gt;Hola, mundo&lt;/saludo&gt;
            </ejemplo>

            <subtitulo>DTD externa</subtitulo>

            <parrafo>Se almacena en un archivo separado y puede ser referenciada por múltiples documentos XML, evitando la redundancia.</parrafo>
            <ejemplo>
    &lt;!DOCTYPE saludo SYSTEM "saludo.dtd"&gt;
    &lt;saludo&gt;Hola, mundo&lt;/saludo&gt;
            </ejemplo>
            <parrafo>La DTD saludo.dtd contendría:</parrafo>
            <ejemplo>
    &lt;!ELEMENT saludo (#PCDATA)&gt;
            </ejemplo>


            <subtitulo>Declaración de Elementos en DTD</subtitulo>
            <parrafo>Para definir un elemento dentro de una DTD se utiliza la siguiente sintaxis:</parrafo>
            <ejemplo>
    &lt;!ELEMENT nombre_elemento tipo_de_contenido&gt;
            </ejemplo>
            <parrafo>Donde tipo_de_contenido puede ser:</parrafo>
            <lista>
                <item>#PCDATA: Contenido de texto.</item>
                <item>EMPTY: Elemento vacío.</item>
                <item>ANY: Puede contener cualquier tipo de datos.</item>
                <item>Una secuencia de elementos hijos.</item>
            </lista>

            <parrafo>Ejemplo de un elemento "persona": </parrafo>
            <ejemplo>
    &lt;!ELEMENT persona (#PCDATA)&gt;
            </ejemplo>


            <subtitulo>Declaración de Atributos en DTD</subtitulo>
            <parrafo>Los atributos se definen con la siguiente sintaxis: </parrafo>
            <ejemplo>
    &lt;ATTLIST nombre_elemento nombre_atributo tipo_de_contenido #modificador&gt;
            </ejemplo>
            <parrafo>El atributo edad debe ser obligatorio y contener texto.</parrafo>
            <parrafo>Tipos de atributos en DTD: </parrafo>
            <lista>
                <item>CDATA: Contiene datos en formato de texto.</item>
                <item>ID: Identificador único dentro del documento.</item>
                <item>IDREF: Referencia a un atributo ID existente.</item>
                <item>Enumerados: Lista de valores posibles.</item>
